version: "3.5"

services:
  db:
    image: library/mysql:5.6
    environment:
      - MYSQL_DATABASE=homefs
      - MYSQL_USER=homefs
      - MYSQL_PASSWORD=homefs
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - mysql-data:/var/lib/mysql
  migrate:
    restart: on-failure
    build:
      context: migrate
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_DATABASE=homefs
      - MYSQL_USER=homefs
      - MYSQL_PASSWORD=homefs
    depends_on:
      - db
  indexer:
    restart: on-failure
    build:
      context: indexer
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_DATABASE=homefs
      - MYSQL_USER=homefs
      - MYSQL_PASSWORD=homefs
    volumes:
      - ./content:/content:ro
    depends_on:
      - db
volumes:
  mysql-data:
    driver: local
