CREATE TABLE `extensions`
(
    `extension` varchar(32)                                                                     NOT NULL,
    `type`      enum ('image','audio','disk-image','archive','temp','document','video','other') NOT NULL DEFAULT 'other',
    PRIMARY KEY (`extension`)
) ENGINE = InnoDB;

INSERT INTO `extensions`
VALUES ('3gp', 'video'),
       ('669', 'audio'),
       ('7z', 'archive'),
       ('ape', 'audio'),
       ('arj', 'archive'),
       ('avi', 'video'),
       ('bin', 'disk-image'),
       ('bmp', 'image'),
       ('cfg', 'other'),
       ('conf', 'other'),
       ('cue', 'disk-image'),
       ('dll', 'other'),
       ('dmf', 'audio'),
       ('doc', 'document'),
       ('docx', 'document'),
       ('exe', 'other'),
       ('far', 'audio'),
       ('flac', 'audio'),
       ('flv', 'video'),
       ('gif', 'image'),
       ('gz', 'archive'),
       ('ico', 'image'),
       ('ini', 'other'),
       ('iso', 'disk-image'),
       ('isz', 'disk-image'),
       ('jpeg', 'image'),
       ('jpg', 'image'),
       ('lz', 'archive'),
       ('m4a', 'audio'),
       ('mkv', 'video'),
       ('mod', 'audio'),
       ('mp1', 'audio'),
       ('mp2', 'audio'),
       ('mp3', 'audio'),
       ('mp4', 'video'),
       ('mpeg', 'video'),
       ('mpg', 'video'),
       ('msi', 'other'),
       ('mtm', 'audio'),
       ('nrg', 'disk-image'),
       ('ogg', 'audio'),
       ('pdf', 'document'),
       ('png', 'image'),
       ('rar', 'archive'),
       ('s3m', 'audio'),
       ('stm', 'audio'),
       ('tif', 'image'),
       ('tta', 'audio'),
       ('txt', 'document'),
       ('ult', 'audio'),
       ('vob', 'video'),
       ('wav', 'audio'),
       ('wma', 'audio'),
       ('wmv', 'video'),
       ('xm', 'audio'),
       ('zip', 'archive');
