name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-migrate:
    name: Build migrate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pldin601/homefs-migrate
          tags: latest
          context: migrate
  build-indexer:
    name: Build indexer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pldin601/homefs-indexer
          tags: latest
          context: indexer
  build-web:
    name: Build web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pldin601/homefs-web
          tags: latest
          context: web
#  deploy:
#    needs:
#      - build-migrate
#      - build-indexer
#      - build-web
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@master
#      - name: Push stack to production
#        uses: pldin601/docker-swarm-deploy-action@master
#        with:
#          remote_host: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_IP_ADDRESS }}
#          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
#          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
#          args: stack deploy --with-registry-auth --prune --resolve-image=always --compose-file docker/docker-compose.production.yml musicloud
